repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace # Trailing whitespace checker
    -   id: check-yaml # Check for YAML syntax errors
    -   id: check-json # Check for JSON syntax errors
    -   id: debug-statements # Check for pdb, ipdb, and print statements
    -   id: end-of-file-fixer # Ensure files end in a newline
    # -   id: check-added-large-files # Prevent large files from being committed
    -   id: check-merge-conflict # Check for files that contain merge conflict strings
    -   id: check-symlinks # Check for symlinks which would be broken in checkout

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        name: black
        types: [python]
        description: 'Black is an uncompromising Python code formatter'

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        name: isort
        types: [python]
        description: 'isort is a Python utility for sorting imports'
        args: ["--profile", "black"] # REQUIRED, otherwise might have infinite loop
                                     # because of black-isort disagreement

-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        name: flake8
        types: [python]
        description: 'Flake8 is a tool for enforcing coding style in Python code'
        args: [
            '--max-line-length=300',
            '--extend-ignore=E203'  # black compat: whitespace before ':'
        ]

# -   repo: https://github.com/PyCQA/bandit
#     rev: 1.8.6
#     hooks:
#     -   id: bandit
#         name: bandit
#         description: 'Bandit is a tool for finding common security issues in Python code'
#         types: [python]

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
    - id: detect-secrets
      description: 'Detect secrets in code to prevent sensitive data leaks'
