
version: "3.8"

services:

  dns:
    build: infrastructure/dns
    env_file:
      - infrastructure/dns/.env
    volumes:
      - ./infrastructure/dns/logs:/app/logs/
    restart: always

  nginx_internal:
    image: nginx
    volumes:
      # SSL Certificates
      - ./infrastructure/nginx_internal/certs:/certs/internal:ro
      - ./infrastructure/nginx_edge/certs/nginxEdge.crt:/certs/edge/nginxEdge.crt:ro
      - ./ca.crt:/certs/ca.crt:ro
      # Nginx config file
      - ./infrastructure/nginx_internal/config:/etc/nginx/conf.d:ro
      # Nginx static files
      - ./infrastructure/nginx_internal/html:/app/html:ro
    networks:
      - app_net
    depends_on:
      - debug_nginx_internal
      - invoice
    ports:
      - "8443:8443"
    restart: always

  debug_nginx_internal:
    build: services/debug_nginx
    networks:
      - app_net
    restart: always

  #tgbot:
  #  build:
  #    dockerfile: services/tgbot/Dockerfile
#
  #  restart: always
  #  networks:
  #    - app_net

  invoice:
    build: services/self-employed
    networks:
      - app_net
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor-arm64:v0.49.1  # Use the version that matches your needs
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: always

networks:
  app_net:
    driver: bridge
