
version: "3.8"

services:

  dns:
    build: infrastructure/dns
    env_file:
      - infrastructure/dns/.env
    volumes:
      - ./infrastructure/dns/logs:/app/logs/

  nginx_internal:
    image: nginx
    volumes:
      # SSL Certificates
      - ./infrastructure/nginx_internal/certs:/certs/internal:ro
      - ./infrastructure/nginx_edge/certs/nginxEdge.crt:/certs/edge/nginxEdge.crt:ro
      - ./ca.crt:/certs/ca.crt:ro
      # Nginx config file
      - ./infrastructure/nginx_internal/config:/etc/nginx/conf.d:ro
      # Nginx static files
      - ./infrastructure/nginx_internal/html:/app/html:ro
    networks:
      - app_net
    depends_on:
      - debug_nginx_internal
      - invoice
    ports:
      - "8443:8443"

  debug_nginx_internal:
    build: services/debug_nginx
    networks:
      - app_net

  tgbot:
    build:
      dockerfile: services/tgbot/Dockerfile

    restart: always
    networks:
      - app_net

  invoice:
    build: services/self-employed
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
