
version: "3.8"

services:

  nginx_edge:
    image: nginx
    ports:
      - "80:80"  # HTTP
      - "443:443" # HTTPS
    volumes:
      # SSL Certificates
      - ./infrastructure/nginx_edge/certs:/certs/edge:ro                                           # certs with public internet
      - ./infrastructure/nginx_internal/certs/nginxInternal.crt:/certs/internal/nginxInternal.crt   # cert of nginx internal
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      # Nginx config file
      - ./infrastructure/nginx_edge/config:/etc/nginx/conf.d:ro
      # Nginx static files
      - ./infrastructure/nginx_edge/html:/usr/share/nginx/html:ro

    restart: always
    # command: ["/bin/sh", "-c", "while :; do sleep 1; done"] # debugging
    networks:
      - revproxy_net
    depends_on:
      - vouch
      - debug_nginx_edge
    extra_hosts:
      # access host's network to forward requests to nginx internal, see https://stackoverflow.com/a/24326540/11552622
      - "host.docker.internal:host-gateway"

  vouch:
    image: voucher/vouch-proxy
    # do NOT expose ports: nginx-vouch communication occurs within docker bridge network
    #                      more secure since I didn't set up SSL between nginx-vouch
    volumes:
      - ./infrastructure/vouch/config:/config:ro

    networks:
      - revproxy_net
    env_file:
      - ./infrastructure/vouch/.env

  debug_nginx_edge:
    build: services/debug_nginx
    networks:
      - revproxy_net

networks:
  revproxy_net:
    driver: bridge
