
version: "3.8"

services:

  nginx:
    image: nginx
    ports:
      - "80:80"  # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:ro
      - ./config/nginx:/certs/:ro
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - ./services/nginx/html:/usr/share/nginx/html:ro
    restart: always
    # command: ["/bin/sh", "-c", "while :; do sleep 1; done"] # debugging
    networks:
      - revproxy_net
    depends_on:
      - vouch

  vouch:
    image: voucher/vouch-proxy
    ports:
      - "9090:9090"
    volumes:
      - ./config/vouch:/config:ro

    networks:
      - revproxy_net

networks:
  revproxy_net:
    driver: bridge
