
# API Roles and Permissions
api_roles:

  # Define roles for API access
  dummy_service:
    # List of tasks this role can access
    - "send_message_admin"

  admin_role:
    # Admin role has access to all endpoints
    - "*"

# Telegram Roles and Permissions
tg_roles:
  # Define roles for Telegram command access

  standard_user:
    - "/start"
    - "/help"

  admin_user:
    - "*"

# This section is described conceptually in permissions.yaml but implemented via .env for security
# service_users:
#   "api_key_for_data_service": "data_service"
#   "api_key_for_analytics_service": "analytics_service"
# telegram_users:
#   "123456789": "basic_user"
#   "987654321": "premium_user"
# --- would be encoded in the .env file as:
## Service Users (API keys to roles)
#API_KEY_FOR_DATA_SERVICE=<actual_key>,role_1,role_2
#API_KEY_FOR_ANALYTICS_SERVICE=<actual_key>,role_2,role_3
#
## Telegram Users (User IDs to roles)
#TELEGRAM_USER_123456789=basic_user
#TELEGRAM_USER_987654321=premium_user
